services:
  redis:
    image: redis:8.0.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - NODE_ENV=development
      - REDIS_USERNAME=redis
      - REDIS_PASSWORD=redis
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 1024M